import Head from "next/head";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import HomeSlider from "@/components/HomeSlider";
import ProductList from "@/components/products/ProductList";
import CategoryList from "@/components/category/CategoryList";
import Footer from "@/components/Footer";
import FeatureProducts from "@/components/products/FeatureProducts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
        <Head>
          <title>eCommerce </title>
          <meta name="description" content="Generated by eCommerce" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <HomeSlider />
        <main className="">
          <CategoryList />
          <ProductList />
          <FeatureProducts />
        </main>
        <Footer />
    </>
  );
}
