import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import HomeSlider from "@/components/HomeSlider";
import ProductList from "@/components/products/ProductList";
import CategoryList from "@/components/category/CategoryList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeSlider />
      <main className="">
        <CategoryList />
        <ProductList />
      </main>
    </>
  );
}
